language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests  --with-coverage --cover-package=GitHubCity --cover-package=GitHubUser testGitHubCity.py testGitHubUser.py -v
after_success:
  - coveralls
