language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests  --with-coverage --cover-package=ghcity --cover-package=ghuser testGitHubUser.py testGitHubCity.py -v
after_success:
  - coveralls
